# Generated by Django 6.0.2 on 2026-05-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('step', models.IntegerField()),
                ('message', models.TextField()),
                ('expected_input', models.TextField(blank=True, null=True)),
                ('next_step', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
