# Generated by Django 6.0.2 on 2026-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lesson_alter_otp_created_at_alter_otp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_last_step',
            field=models.BooleanField(default=False),
        ),
    ]
