# Generated by Django 6.0.2 on 2026-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='validation_type',
            field=models.CharField(default='contains', max_length=50),
        ),
    ]
