# Generated by Django 6.0.2 on 2026-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lesson_validation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
