# Generated by Django 6.0.2 on 2026-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprogress_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='min_words',
            field=models.IntegerField(default=0),
        ),
    ]
