# Generated by Django 6.0.2 on 2026-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lesson_min_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
