# Generated by Django 6.0.2 on 2026-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprogress_phone_userprogress_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='message_marathi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
